---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: schizo-bot
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/jay123q/schizo-bot.git
  ref:
    branch: main
